// src/sub-pack-2/tresjs-demo/examples/OrbitControls.vue
<template>
    <TresCanvas v-bind="gl">
        <TresPerspectiveCamera :position="[4, 3, 9]" />
        <OrbitControls />
        <Suspense>
            <Text3D
                    :position="[0, 1, 0]"
                    text="Hello three.js"
                    font="https://threejs.org/examples/fonts/helvetiker_regular.typeface.json"
            >
                <TresMeshNormalMaterial/>
            </Text3D>
        </Suspense>
        <TresDirectionalLight :position="[0, 2, 4]" :intensity="1.2" cast-shadow />
        <TresGridHelper />
    </TresCanvas>
</template>
<script setup lang="ts">
import { BasicShadowMap, SRGBColorSpace, NoToneMapping } from 'three';
import { TresCanvas } from '@tresjs/core';
import { OrbitControls, Text3D } from '@tresjs/cientos';

const gl = {
  clearColor: '#82DBC5',
  shadows: true,
  alpha: false,
  shadowMapType: BasicShadowMap,
  outputColorSpace: SRGBColorSpace,
  toneMapping: NoToneMapping,
};
</script>

// src/sub-pack-2/r3f-examples/base/OrbitControls.tsx
import { useThree } from "@react-three/fiber";
import { useEffect } from "react";
import { OrbitControls, Text3D, Grid, Center } from "@react-three/drei";
import React from "react";

export function OrbitControlsDemo() {
  const camera = useThree((state) => state.camera);
  useEffect(() => {
    camera.position.set(4, 3, 9)
  }, [camera]);
  return (<>
    <OrbitControls makeDefault></OrbitControls>
    <React.Suspense>
      <Center position={[0, 1, 0]}>
        <Text3D font="https://threejs.org/examples/fonts/helvetiker_regular.typeface.json">
          Hello three.js
        </Text3D>
      </Center>
    </React.Suspense>
    <Grid args={[10, 10]}/>
    <directionalLight position={[0, 2, 4]} intensity={1.2} castShadow></directionalLight>
  </>)
}
